delete from parametroglobal;
delete from pratica_acao;
delete from instancia_acao;
delete from vara_aud;
--delete from instancia_aud;
delete from pratica_aud;
delete from acao_aud;
--delete from instancia - foi gravada pelo migrate;
delete from pratica;
delete from acao;
delete  from vara;
